// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmMn_xSpk3HZWzgtJDttNyqrVaaWzLsvw',
    appId: '1:662320347384:web:0ca36f98cf66d2a5a3e30d',
    messagingSenderId: '662320347384',
    projectId: 'yogcare',
    authDomain: 'yogcare.firebaseapp.com',
    storageBucket: 'yogcare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdIPbLfV-G8o0hJ9fNm2lcxVTkS5NQE4',
    appId: '1:662320347384:android:d31d97174b289820a3e30d',
    messagingSenderId: '662320347384',
    projectId: 'yogcare',
    storageBucket: 'yogcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWS5d5gNnqMf028zY7PxSHtqiYfzm_IOc',
    appId: '1:662320347384:ios:72757cd8a7cc3f02a3e30d',
    messagingSenderId: '662320347384',
    projectId: 'yogcare',
    storageBucket: 'yogcare.appspot.com',
    iosClientId: '662320347384-j7cshaa82q83r5n5r90so3bmot3tnb2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWS5d5gNnqMf028zY7PxSHtqiYfzm_IOc',
    appId: '1:662320347384:ios:72757cd8a7cc3f02a3e30d',
    messagingSenderId: '662320347384',
    projectId: 'yogcare',
    storageBucket: 'yogcare.appspot.com',
    iosClientId: '662320347384-j7cshaa82q83r5n5r90so3bmot3tnb2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaApp',
  );
}
